// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9_7-aaqYrTnRcGNR2qXITYHpfdyz04b0',
    appId: '1:705410372549:web:ad0948e68f8e6e14aaf1ac',
    messagingSenderId: '705410372549',
    projectId: 'smartattendance-6f84f',
    authDomain: 'smartattendance-6f84f.firebaseapp.com',
    databaseURL: 'https://smartattendance-6f84f-default-rtdb.firebaseio.com',
    storageBucket: 'smartattendance-6f84f.firebasestorage.app',
    measurementId: 'G-JRGTLK02H7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9_7-aaqYrTnRcGNR2qXITYHpfdyz04b0',
    appId: '1:705410372549:android:690166a42682f212aaf1ac',
    messagingSenderId: '705410372549',
    projectId: 'smartattendance-6f84f',
    databaseURL: 'https://smartattendance-6f84f-default-rtdb.firebaseio.com',
    storageBucket: 'smartattendance-6f84f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9_7-aaqYrTnRcGNR2qXITYHpfdyz04b0',
    appId: '1:705410372549:ios:3cfe4fe7605c86edaaf1ac',
    messagingSenderId: '705410372549',
    projectId: 'smartattendance-6f84f',
    databaseURL: 'https://smartattendance-6f84f-default-rtdb.firebaseio.com',
    storageBucket: 'smartattendance-6f84f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9_7-aaqYrTnRcGNR2qXITYHpfdyz04b0',
    appId: '1:705410372549:ios:3cfe4fe7605c86edaaf1ac',
    messagingSenderId: '705410372549',
    projectId: 'smartattendance-6f84f',
    databaseURL: 'https://smartattendance-6f84f-default-rtdb.firebaseio.com',
    storageBucket: 'smartattendance-6f84f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9_7-aaqYrTnRcGNR2qXITYHpfdyz04b0',
    appId: '1:705410372549:web:47b447a8ad566bafaaf1ac',
    messagingSenderId: '705410372549',
    projectId: 'smartattendance-6f84f',
    authDomain: 'smartattendance-6f84f.firebaseapp.com',
    databaseURL: 'https://smartattendance-6f84f-default-rtdb.firebaseio.com',
    storageBucket: 'smartattendance-6f84f.firebasestorage.app',
    measurementId: 'G-HMR29NZHXS',
  );
}
